{"kind":"symbol","abstract":[{"text":"휴대폰안심 서비스 SDK","type":"text"}],"metadata":{"role":"collection","roleHeading":"Framework","modules":[{"name":"PhoneSafeFramework"}],"symbolKind":"module","title":"PhoneSafeFramework","externalID":"PhoneSafeFramework"},"topicSections":[{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/ImageAnimator","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeAPI","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeBrowsingClass","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeSDKEnvironment","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/SharedUserDefaultsManager"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeDelegate"]},{"title":"Structures","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/BiometricInfo","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/DeviceInfo","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/SubscribeFCMInfo"]},{"title":"Enumerations","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/APIEndpoint","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/BioRegistrationState","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/EmbededType","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/LoadingActivation","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/TopRightButtonType","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/UserDefaultsKey"]}],"sections":[],"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/phonesafeframework"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/phonesafeframework"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeFrameworkVersionString":{"abstract":[{"type":"text","text":"Project version string for PhoneSafeFramework."}],"kind":"symbol","url":"\/documentation\/phonesafeframework\/phonesafeframeworkversionstring","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeFrameworkVersionString","type":"topic","title":"PhoneSafeFrameworkVersionString","fragments":[{"kind":"identifier","text":"PhoneSafeFrameworkVersionString"}],"role":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/EmbededType":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/EmbededType","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmbededType"}],"title":"EmbededType","navigatorTitle":[{"text":"EmbededType","kind":"identifier"}],"url":"\/documentation\/phonesafeframework\/embededtype"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/ImageAnimator":{"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/imageanimator","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageAnimator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageAnimator"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/ImageAnimator","title":"ImageAnimator"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeBrowsingClass":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeBrowsingClass","type":"topic","title":"PhoneSafeBrowsingClass","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PhoneSafeBrowsingClass","kind":"identifier"}],"url":"\/documentation\/phonesafeframework\/phonesafebrowsingclass","navigatorTitle":[{"kind":"identifier","text":"PhoneSafeBrowsingClass"}]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/TopRightButtonType":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/TopRightButtonType","url":"\/documentation\/phonesafeframework\/toprightbuttontype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TopRightButtonType","kind":"identifier"}],"abstract":[{"type":"text","text":"네비게이션바의 우상단 버튼 타입"}],"role":"symbol","title":"TopRightButtonType","kind":"symbol","navigatorTitle":[{"text":"TopRightButtonType","kind":"identifier"}]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/SharedUserDefaultsManager":{"title":"SharedUserDefaultsManager","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/SharedUserDefaultsManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharedUserDefaultsManager"}],"navigatorTitle":[{"kind":"identifier","text":"SharedUserDefaultsManager"}],"type":"topic","role":"symbol","url":"\/documentation\/phonesafeframework\/shareduserdefaultsmanager","abstract":[{"type":"text","text":"App Group을 기반으로 동작되는 User Defaults값"}]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/LoadingActivation":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/LoadingActivation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoadingActivation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"LoadingActivation","kind":"identifier"}],"title":"LoadingActivation","url":"\/documentation\/phonesafeframework\/loadingactivation"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeSDKEnvironment":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PhoneSafeSDKEnvironment"}],"abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeSDKEnvironment","title":"PhoneSafeSDKEnvironment","kind":"symbol","url":"\/documentation\/phonesafeframework\/phonesafesdkenvironment","navigatorTitle":[{"text":"PhoneSafeSDKEnvironment","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeFrameworkVersionNumber":{"abstract":[{"type":"text","text":"Project version number for PhoneSafeFramework."}],"kind":"symbol","url":"\/documentation\/phonesafeframework\/phonesafeframeworkversionnumber","type":"topic","role":"symbol","fragments":[{"text":"PhoneSafeFrameworkVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeFrameworkVersionNumber","title":"PhoneSafeFrameworkVersionNumber"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/APIEndpoint":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/APIEndpoint","title":"APIEndpoint","url":"\/documentation\/phonesafeframework\/apiendpoint","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"APIEndpoint","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"APIEndpoint","kind":"identifier"}]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/SubscribeFCMInfo":{"role":"symbol","kind":"symbol","url":"\/documentation\/phonesafeframework\/subscribefcminfo","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubscribeFCMInfo"}],"navigatorTitle":[{"kind":"identifier","text":"SubscribeFCMInfo"}],"title":"SubscribeFCMInfo","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/SubscribeFCMInfo","abstract":[]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/UserDefaultsKey":{"url":"\/documentation\/phonesafeframework\/userdefaultskey","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserDefaultsKey"}],"kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/UserDefaultsKey","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserDefaultsKey"}],"title":"UserDefaultsKey","abstract":[],"type":"topic"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeDelegate":{"title":"PhoneSafeDelegate","url":"\/documentation\/phonesafeframework\/phonesafedelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PhoneSafeDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeDelegate","navigatorTitle":[{"text":"PhoneSafeDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"사용하지 않는 delegate는 코드블럭을 빈칸으로 둡니다."}],"role":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeAPI":{"type":"topic","url":"\/documentation\/phonesafeframework\/phonesafeapi","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PhoneSafeAPI"}],"navigatorTitle":[{"text":"PhoneSafeAPI","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeAPI","title":"PhoneSafeAPI","kind":"symbol","abstract":[]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/DeviceInfo":{"url":"\/documentation\/phonesafeframework\/deviceinfo","abstract":[],"title":"DeviceInfo","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DeviceInfo"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DeviceInfo","kind":"identifier"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/DeviceInfo"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/BiometricInfo":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/BiometricInfo","title":"BiometricInfo","url":"\/documentation\/phonesafeframework\/biometricinfo","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BiometricInfo"}],"navigatorTitle":[{"kind":"identifier","text":"BiometricInfo"}],"role":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/BioRegistrationState":{"abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/BioRegistrationState","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BioRegistrationState","kind":"identifier"}],"title":"BioRegistrationState","navigatorTitle":[{"text":"BioRegistrationState","kind":"identifier"}],"type":"topic","url":"\/documentation\/phonesafeframework\/bioregistrationstate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"]},{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeFrameworkVersionNumber","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeFrameworkVersionString"],"title":"Variables"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","value":"PhoneSafeViewController"},{"value":[{"text":"PhoneSafeViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}