{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"variants":[{"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller"]}],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/init(targetView:url:delegateReceiver:)"]},{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/delegate"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/finishSDK()","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/loadURL(_:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/observeValue(forKeyPath:of:change:context:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/traitCollectionDidChange(_:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userNotificationCenter(_:didReceive:withCompletionHandler:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userNotificationCenter(_:willPresent:withCompletionHandler:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/viewDidLoad()","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/viewWillAppear(_:)"],"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/CLLocationManagerDelegate-Implementations","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKScriptMessageHandler-Implementations"],"generated":true}],"metadata":{"modules":[{"name":"PhoneSafeFramework"}],"role":"symbol","title":"PhoneSafeViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhoneSafeViewController"}],"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@PhoneSafeFramework@objc(cs)PhoneSafeViewController"},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)CLLocationManagerDelegate","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)NSCoding","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)NSObject","doc:\/\/com.atoncorp.phonesafeframework\/s7CVarArgP","doc:\/\/com.atoncorp.phonesafeframework\/s28CustomDebugStringConvertibleP","doc:\/\/com.atoncorp.phonesafeframework\/s23CustomStringConvertibleP","doc:\/\/com.atoncorp.phonesafeframework\/SQ","doc:\/\/com.atoncorp.phonesafeframework\/SH","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIAppearanceContainer","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIContentContainer","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIFocusEnvironment","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIStateRestoring","doc:\/\/com.atoncorp.phonesafeframework\/5UIKit23UITraitChangeObservableP","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UITraitEnvironment","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIUserActivityRestoring","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKNavigationDelegate","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKScriptMessageHandler","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKUIDelegate"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.atoncorp.phonesafeframework/objc(pl)WKUIDelegate":{"type":"unresolvable","title":"WKUIDelegate","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKUIDelegate"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIContentContainer"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/loadURL(_:)":{"title":"loadURL(_:)","kind":"symbol","abstract":[{"type":"text","text":"안심SDK로 접근하려는 주소를 넣어주세요."}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/loadURL(_:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/loadurl(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadURL"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.atoncorp.phonesafeframework/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)NSCoding"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/observeValue(forKeyPath:of:change:context:)":{"kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/observeValue(forKeyPath:of:change:context:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKeyPath","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"of"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"change"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSKeyValueChangeKey","preciseIdentifier":"c:@T@NSKeyValueChangeKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"type":"topic","title":"observeValue(forKeyPath:of:change:context:)","navigatorTitle":[{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/observevalue(forkeypath:of:change:context:)"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/viewWillAppear(_:)":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/viewWillAppear(_:)","role":"symbol"},"doc://com.atoncorp.phonesafeframework/objc(pl)CLLocationManagerDelegate":{"type":"unresolvable","title":"CLLocationManagerDelegate","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)CLLocationManagerDelegate"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/WKNavigationDelegate-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wknavigationdelegate-implementations","role":"collectionGroup","type":"topic","title":"WKNavigationDelegate Implementations","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://com.atoncorp.phonesafeframework/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UITraitEnvironment"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/WKScriptMessageHandler-Implementations":{"title":"WKScriptMessageHandler Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKScriptMessageHandler-Implementations","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wkscriptmessagehandler-implementations","type":"topic","role":"collectionGroup"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/viewDidLoad()":{"type":"topic","title":"viewDidLoad()","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/viewdidload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/delegate":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/delegate","type":"topic","title":"delegate","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18PhoneSafeFramework0aB8DelegateP","text":"PhoneSafeDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/delegate"},"doc://com.atoncorp.phonesafeframework/SH":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.atoncorp.phonesafeframework/objc(pl)WKNavigationDelegate":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKNavigationDelegate","title":"WKNavigationDelegate","type":"unresolvable"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIResponderStandardEditActions"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIStateRestoring"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/userNotificationCenter(_:willPresent:withCompletionHandler:)":{"type":"topic","title":"userNotificationCenter(_:willPresent:withCompletionHandler:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/usernotificationcenter(_:willpresent:withcompletionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userNotificationCenter","kind":"identifier"},{"kind":"text","text":"("},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willPresent"},{"kind":"text","text":": "},{"text":"UNNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotification"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@UNNotificationPresentationOptions","text":"UNNotificationPresentationOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userNotificationCenter(_:willPresent:withCompletionHandler:)","kind":"symbol"},"doc://com.atoncorp.phonesafeframework/objc(pl)WKScriptMessageHandler":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKScriptMessageHandler","title":"WKScriptMessageHandler","type":"unresolvable"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/init(targetView:url:delegateReceiver:)":{"title":"init(targetView:url:delegateReceiver:)","kind":"symbol","abstract":[{"text":"초기화 메서드로, PhoneSafe를 NavigationController에 담아 Present 방식으로 띄웁니다.","type":"text"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/init(targetView:url:delegateReceiver:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/init(targetview:url:delegatereceiver:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"targetView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"delegateReceiver","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18PhoneSafeFramework0aB8DelegateP","text":"PhoneSafeDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.atoncorp.phonesafeframework/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.atoncorp.phonesafeframework/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(cs)UIViewController","title":"UIViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/finishSDK()":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/finishsdk()","type":"topic","title":"finishSDK()","kind":"symbol","abstract":[{"type":"text","text":"안심SDK화면을 내리고 메모리에서 해제합니다."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finishSDK"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/finishSDK()"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.atoncorp.phonesafeframework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/CLLocationManagerDelegate-Implementations":{"title":"CLLocationManagerDelegate Implementations","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/cllocationmanagerdelegate-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/CLLocationManagerDelegate-Implementations","role":"collectionGroup","abstract":[]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/userNotificationCenter(_:didReceive:withCompletionHandler:)":{"type":"topic","title":"userNotificationCenter(_:didReceive:withCompletionHandler:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/usernotificationcenter(_:didreceive:withcompletionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userNotificationCenter","kind":"identifier"},{"kind":"text","text":"("},{"text":"UNUserNotificationCenter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNUserNotificationCenter"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","kind":"typeIdentifier","text":"UNNotificationResponse"},{"text":", ","kind":"text"},{"text":"withCompletionHandler","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userNotificationCenter(_:didReceive:withCompletionHandler:)","kind":"symbol"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.atoncorp.phonesafeframework/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.atoncorp.phonesafeframework/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/SQ","title":"Swift.Equatable"},"doc://com.atoncorp.phonesafeframework/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.atoncorp.phonesafeframework/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.atoncorp.phonesafeframework/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/traitCollectionDidChange(_:)":{"title":"traitCollectionDidChange(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"traitCollectionDidChange:"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/traitCollectionDidChange(_:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/traitcollectiondidchange(_:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PhoneSafeViewController","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PhoneSafeViewController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PhoneSafeViewController"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/observeValue(forKeyPath:of:change:context:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/traitCollectionDidChange(_:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/viewDidLoad()","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/viewWillAppear(_:)"]},{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/CLLocationManagerDelegate-Implementations","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKScriptMessageHandler-Implementations"],"title":"Default Implementations","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)CLLocationManagerDelegate","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKNavigationDelegate","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKScriptMessageHandler","doc:\/\/com.atoncorp.phonesafeframework\/objc(pl)WKUIDelegate"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"PhoneSafeViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"observeValueForKeyPath:ofObject:change:context:","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1observeValue(forKeyPath:of:change:context:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"observeValueForKeyPath:ofObject:change:context:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1observeValue(forKeyPath:of:change:context:)\/fragments"},{"value":"viewWillAppear:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1viewWillAppear(_:)\/title"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1viewWillAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1viewDidLoad()\/fragments"},{"value":"PhoneSafeViewController","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","op":"replace"},{"value":[{"text":"PhoneSafeViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments"},{"value":"traitCollectionDidChange:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1traitCollectionDidChange(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"traitCollectionDidChange:","kind":"identifier"}]}]}]}