{"topicSections":[{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/locationManager(_:didChangeAuthorization:)"],"title":"Instance Methods","generated":true}],"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/CLLocationManagerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"PhoneSafeFramework"}],"title":"CLLocationManagerDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/cllocationmanagerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/cllocationmanagerdelegate-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"]]},"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/locationManager(_:didChangeAuthorization:)":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/locationManager(_:didChangeAuthorization:)","role":"symbol","kind":"symbol","title":"locationManager(_:didChangeAuthorization:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"text":"CLLocationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"text":", ","kind":"text"},{"text":"didChangeAuthorization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@CLAuthorizationStatus","text":"CLAuthorizationStatus","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/locationmanager(_:didchangeauthorization:)","navigatorTitle":[{"kind":"identifier","text":"locationManager:didChangeAuthorizationStatus:"}],"abstract":[]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","navigatorTitle":[{"kind":"identifier","text":"PhoneSafeViewController"}],"title":"PhoneSafeViewController","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PhoneSafeViewController"}],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/locationManager(_:didChangeAuthorization:)"],"generated":true,"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"locationManager:didChangeAuthorizationStatus:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1locationManager(_:didChangeAuthorization:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1locationManager(_:didChangeAuthorization:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"locationManager:didChangeAuthorizationStatus:"}]},{"value":"PhoneSafeViewController","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title"},{"value":[{"text":"PhoneSafeViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}