{"metadata":{"title":"traitCollectionDidChange(_:)","navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"modules":[{"name":"PhoneSafeFramework"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@PhoneSafeFramework@objc(cs)PhoneSafeViewController(im)traitCollectionDidChange:","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"]]},"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/traitCollectionDidChange(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/traitcollectiondidchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/traitcollectiondidchange(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"traitCollectionDidChange"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"previousTraitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"languages":["swift"]}]}],"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/traitCollectionDidChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollectionDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"traitCollectionDidChange:","kind":"identifier"}],"title":"traitCollectionDidChange(_:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/traitcollectiondidchange(_:)","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/traitCollectionDidChange(_:)","role":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","navigatorTitle":[{"kind":"identifier","text":"PhoneSafeViewController"}],"title":"PhoneSafeViewController","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PhoneSafeViewController"}],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"traitCollectionDidChange:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"traitCollectionDidChange:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"traitCollectionDidChange:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"previousTraitCollection"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"traitCollectionDidChange:","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1traitCollectionDidChange(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1traitCollectionDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"traitCollectionDidChange:"}]},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","op":"replace","value":"PhoneSafeViewController"},{"value":[{"text":"PhoneSafeViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}