{"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didfinish:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didfinish:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"WKNavigationDelegate.webView(_:didFinish:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFinish:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":", "},{"text":"didFinish","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinish"},{"text":": ","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"title":"webView(_:didFinish:)","modules":[{"name":"PhoneSafeFramework"}],"navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}],"extendedModule":"PhoneSafeFramework","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@CM@PhoneSafeFramework@objc(cs)PhoneSafeViewController(im)webView:didFinishNavigation:"},"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didFinish:)":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFinish:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didfinish:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinish"},{"kind":"text","text":": "},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"webView:didFinishNavigation:"}],"abstract":[],"title":"webView(_:didFinish:)","kind":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","navigatorTitle":[{"kind":"identifier","text":"PhoneSafeViewController"}],"title":"PhoneSafeViewController","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PhoneSafeViewController"}],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/WKNavigationDelegate-Implementations":{"kind":"article","title":"WKNavigationDelegate Implementations","type":"topic","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wknavigationdelegate-implementations","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"webView:didFinishNavigation:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:didFinishNavigation:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":" *) "},{"text":"webView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishNavigation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier","text":"WKNavigation"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"webView:didFinishNavigation:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFinish:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"webView:didFinishNavigation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFinish:)\/fragments"},{"value":"PhoneSafeViewController","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","value":[{"text":"PhoneSafeViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}