{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didStartProvisionalNavigation:)"},"kind":"symbol","metadata":{"title":"webView(_:didStartProvisionalNavigation:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStartProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"text":"webView:didStartProvisionalNavigation:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@CM@PhoneSafeFramework@objc(cs)PhoneSafeViewController(im)webView:didStartProvisionalNavigation:","modules":[{"name":"PhoneSafeFramework"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:didStartProvisionalNavigation:)"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartProvisionalNavigation"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didstartprovisionalnavigation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didstartprovisionalnavigation:)"]}],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations"]]},"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","navigatorTitle":[{"kind":"identifier","text":"PhoneSafeViewController"}],"title":"PhoneSafeViewController","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PhoneSafeViewController"}],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/WKNavigationDelegate-Implementations":{"kind":"article","title":"WKNavigationDelegate Implementations","type":"topic","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wknavigationdelegate-implementations","role":"collectionGroup","abstract":[]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didStartProvisionalNavigation:)":{"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didStartProvisionalNavigation:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didstartprovisionalnavigation:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didStartProvisionalNavigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"title":"webView(_:didStartProvisionalNavigation:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"webView:didStartProvisionalNavigation:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"webView:didStartProvisionalNavigation:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"text":" ","kind":"text"},{"text":"didStartProvisionalNavigation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"PhoneSafeViewController","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"PhoneSafeViewController"}]},{"value":"webView:didStartProvisionalNavigation:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didStartProvisionalNavigation:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"webView:didStartProvisionalNavigation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didStartProvisionalNavigation:)\/fragments"}]}]}