{"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"locationManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeAuthorization","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CLAuthorizationStatus","preciseIdentifier":"c:@E@CLAuthorizationStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"locationManager(_:didChangeAuthorization:)","roleHeading":"Instance Method","externalID":"c:@CM@PhoneSafeFramework@objc(cs)PhoneSafeViewController(im)locationManager:didChangeAuthorizationStatus:","navigatorTitle":[{"text":"locationManager:didChangeAuthorizationStatus:","kind":"identifier"}],"modules":[{"name":"PhoneSafeFramework"}],"role":"symbol","extendedModule":"PhoneSafeFramework"},"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/locationManager(_:didChangeAuthorization:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/locationmanager(_:didchangeauthorization:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/locationmanager(_:didchangeauthorization:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"locationManager","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CLLocationManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"text":", ","kind":"text"},{"text":"didChangeAuthorization","kind":"externalParam"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CLAuthorizationStatus","text":"CLAuthorizationStatus","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/CLLocationManagerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"CLLocationManagerDelegate.locationManager(_:didChangeAuthorization:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/locationManager(_:didChangeAuthorization:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/locationManager(_:didChangeAuthorization:)","title":"locationManager(_:didChangeAuthorization:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/locationmanager(_:didchangeauthorization:)","abstract":[],"navigatorTitle":[{"text":"locationManager:didChangeAuthorizationStatus:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"locationManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeAuthorization"},{"kind":"text","text":": "},{"text":"CLAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@CLAuthorizationStatus"},{"kind":"text","text":")"}]},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/CLLocationManagerDelegate-Implementations":{"title":"CLLocationManagerDelegate Implementations","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/cllocationmanagerdelegate-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/CLLocationManagerDelegate-Implementations","role":"collectionGroup","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"locationManager:didChangeAuthorizationStatus:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didChangeAuthorizationStatus:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"locationManager:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *) "},{"text":"manager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didChangeAuthorizationStatus:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLAuthorizationStatus","preciseIdentifier":"c:@E@CLAuthorizationStatus","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"PhoneSafeViewController","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","value":[{"kind":"identifier","text":"PhoneSafeViewController"}]},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1locationManager(_:didChangeAuthorization:)\/title","op":"replace","value":"locationManager:didChangeAuthorizationStatus:"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1locationManager(_:didChangeAuthorization:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"locationManager:didChangeAuthorizationStatus:","kind":"identifier"}]}]}]}