{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKScriptMessageHandler-Implementations"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userContentController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userContentController"},{"text":": ","kind":"text"},{"text":"WKUserContentController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKScriptMessage","kind":"typeIdentifier","text":"WKScriptMessage"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userContentController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"kind":"text","text":", "},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"userContentController:didReceiveScriptMessage:","kind":"identifier"}],"externalID":"c:@CM@PhoneSafeFramework@objc(cs)PhoneSafeViewController(im)userContentController:didReceiveScriptMessage:","role":"symbol","modules":[{"name":"PhoneSafeFramework"}],"title":"userContentController(_:didReceive:)"},"variants":[{"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/usercontentcontroller(_:didreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/usercontentcontroller(_:didreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userContentController(_:didReceive:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"WKScriptMessageHandler.userContentController(_:didReceive:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/userContentController(_:didReceive:)":{"type":"topic","title":"userContentController(_:didReceive:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/usercontentcontroller(_:didreceive:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userContentController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userContentController(_:didReceive:)","navigatorTitle":[{"text":"userContentController:didReceiveScriptMessage:","kind":"identifier"}],"kind":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/WKScriptMessageHandler-Implementations":{"title":"WKScriptMessageHandler Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKScriptMessageHandler-Implementations","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wkscriptmessagehandler-implementations","type":"topic","role":"collectionGroup"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"userContentController:didReceiveScriptMessage:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"userContentController:didReceiveScriptMessage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"userContentController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKUserContentController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController"},{"kind":"text","text":" *) "},{"text":"userContentController","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveScriptMessage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKScriptMessage","text":"WKScriptMessage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"userContentController:didReceiveScriptMessage:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1userContentController(_:didReceive:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"userContentController:didReceiveScriptMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1userContentController(_:didReceive:)\/fragments"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","value":"PhoneSafeViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","value":[{"text":"PhoneSafeViewController","kind":"identifier"}]}]}]}