{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didcommit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didcommit:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"webView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCommit"},{"kind":"text","text":" "},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didCommit:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:didCommit:)"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","extendedModule":"PhoneSafeFramework","externalID":"c:@CM@PhoneSafeFramework@objc(cs)PhoneSafeViewController(im)webView:didCommitNavigation:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCommit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"text":"!)","kind":"text"}],"role":"symbol","title":"webView(_:didCommit:)","modules":[{"name":"PhoneSafeFramework"}],"navigatorTitle":[{"kind":"identifier","text":"webView:didCommitNavigation:"}]},"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didCommit:)":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didcommit:)","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didCommit:)","role":"symbol","navigatorTitle":[{"text":"webView:didCommitNavigation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCommit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!)","kind":"text"}],"kind":"symbol","title":"webView(_:didCommit:)","type":"topic"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/WKNavigationDelegate-Implementations":{"kind":"article","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wknavigationdelegate-implementations","role":"collectionGroup","type":"topic","title":"WKNavigationDelegate Implementations","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:didCommitNavigation:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:didCommitNavigation:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"webView:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCommitNavigation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier","text":"WKNavigation"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"navigation"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didCommit:)\/title","value":"webView:didCommitNavigation:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"webView:didCommitNavigation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didCommit:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","value":"PhoneSafeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","value":[{"text":"PhoneSafeViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}