{"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKNavigationDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didCommit:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFail:withError:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFailProvisionalNavigation:withError:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFinish:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didStartProvisionalNavigation:)"],"generated":true,"title":"Instance Methods"}],"metadata":{"title":"WKNavigationDelegate Implementations","role":"collectionGroup","modules":[{"name":"PhoneSafeFramework"}],"roleHeading":"API Collection"},"kind":"article","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wknavigationdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wknavigationdelegate-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didStartProvisionalNavigation:)":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didstartprovisionalnavigation:)","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didStartProvisionalNavigation:)","role":"symbol","navigatorTitle":[{"text":"webView:didStartProvisionalNavigation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStartProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"kind":"text","text":"!)"}],"kind":"symbol","title":"webView(_:didStartProvisionalNavigation:)","type":"topic"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didFail:withError:)":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didfail:witherror:)","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFail:withError:)","role":"symbol","navigatorTitle":[{"text":"webView:didFailNavigation:withError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"kind":"symbol","title":"webView(_:didFail:withError:)","type":"topic"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didFinish:)":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didfinish:)","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFinish:)","role":"symbol","navigatorTitle":[{"text":"webView:didFinishNavigation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinish"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"kind":"symbol","title":"webView(_:didFinish:)","type":"topic"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didCommit:)":{"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didcommit:)","abstract":[],"identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didCommit:)","role":"symbol","navigatorTitle":[{"text":"webView:didCommitNavigation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCommit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!)","kind":"text"}],"kind":"symbol","title":"webView(_:didCommit:)","type":"topic"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/webView(_:didFailProvisionalNavigation:withError:)":{"navigatorTitle":[{"text":"webView:didFailProvisionalNavigation:withError:","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/webview(_:didfailprovisionalnavigation:witherror:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"webView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":", "},{"text":"didFailProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"title":"webView(_:didFailProvisionalNavigation:withError:)","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFailProvisionalNavigation:withError:)"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didCommit:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFail:withError:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFailProvisionalNavigation:withError:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didFinish:)","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/webView(_:didStartProvisionalNavigation:)"]}],"path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didStartProvisionalNavigation:)\/title","value":"webView:didStartProvisionalNavigation:"},{"value":[{"kind":"text","text":"- "},{"text":"webView:didStartProvisionalNavigation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didStartProvisionalNavigation:)\/fragments"},{"op":"replace","value":"PhoneSafeViewController","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","op":"replace","value":[{"text":"PhoneSafeViewController","kind":"identifier"}]},{"value":"webView:didFailNavigation:withError:","op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFail:withError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFail:withError:)\/fragments"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFinish:)\/title","value":"webView:didFinishNavigation:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFinishNavigation:"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFinish:)\/fragments"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didCommit:)\/title","value":"webView:didCommitNavigation:","op":"replace"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didCommit:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didCommitNavigation:"}],"op":"replace"},{"value":"webView:didFailProvisionalNavigation:withError:","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFailProvisionalNavigation:withError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1webView(_:didFailProvisionalNavigation:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"webView:didFailProvisionalNavigation:withError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}