{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework","doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"]]},"sections":[],"identifier":{"url":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/WKScriptMessageHandler-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"WKScriptMessageHandler Implementations","modules":[{"name":"PhoneSafeFramework"}],"role":"collectionGroup"},"kind":"article","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userContentController(_:didReceive:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wkscriptmessagehandler-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/phonesafeframework\/phonesafeviewcontroller\/wkscriptmessagehandler-implementations"]}],"references":{"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController/userContentController(_:didReceive:)":{"type":"topic","title":"userContentController(_:didReceive:)","url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller\/usercontentcontroller(_:didreceive:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userContentController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKUserContentController","text":"WKUserContentController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didReceive"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WKScriptMessage","preciseIdentifier":"c:objc(cs)WKScriptMessage"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userContentController(_:didReceive:)","navigatorTitle":[{"text":"userContentController:didReceiveScriptMessage:","kind":"identifier"}],"kind":"symbol"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework/PhoneSafeViewController":{"navigatorTitle":[{"text":"PhoneSafeViewController","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/phonesafeframework\/phonesafeviewcontroller","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PhoneSafeViewController","kind":"identifier"}],"title":"PhoneSafeViewController","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController"},"doc://com.atoncorp.phonesafeframework/documentation/PhoneSafeFramework":{"abstract":[{"type":"text","text":"휴대폰안심 서비스 SDK"}],"type":"topic","url":"\/documentation\/phonesafeframework","title":"PhoneSafeFramework","role":"collection","kind":"symbol","identifier":"doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.atoncorp.phonesafeframework\/documentation\/PhoneSafeFramework\/PhoneSafeViewController\/userContentController(_:didReceive:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"userContentController:didReceiveScriptMessage:","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1userContentController(_:didReceive:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userContentController:didReceiveScriptMessage:"}],"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController~1userContentController(_:didReceive:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/title","value":"PhoneSafeViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.atoncorp.phonesafeframework~1documentation~1PhoneSafeFramework~1PhoneSafeViewController\/fragments","value":[{"kind":"identifier","text":"PhoneSafeViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}